[package]
name = "music_manager_helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0"
glob = "0.3.0"
id3 = "1.0.2"
clap = { version = "3.1.0", features = ["derive"] }
clap_complete = "3.1.0"
